#!/usr/bin/env bash
# tools/stamp_build.sh — I5 (M1.2): bake the real git short SHA into a git-ignored
# generated artifact (`systems/build_info_gen.gd`) that BuildVersion reads at runtime.
#
# Run this BEFORE an export/build so the produced binary knows its exact commit even
# where `git`/`.git` are absent at runtime (exported Windows build). Called by CI
# (nightly.yml) before --export-release AND runnable locally before a playtest build:
#
#   bash tools/stamp_build.sh
#
# The artifact is git-ignored (a build product), so it can never go stale in source
# the way the old committed `project.godot:config/build_sha` did. An un-stamped build
# (no artifact) falls through to BuildVersion's neutral "0000000" sentinel, making an
# un-stamped binary obvious in the telemetry log.
set -euo pipefail

# Resolve the repo root from this script's location so it works from any CWD.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$REPO_ROOT"

OUT="systems/build_info_gen.gd"

SHA="$(git rev-parse --short HEAD)"
# Q3 (Director-approved): mark an uncommitted working tree with a visible +dirty
# suffix so a build off uncommitted work is impossible to mis-trust as a clean commit.
if [ -n "$(git status --porcelain)" ]; then
	SHA="${SHA}+dirty"
fi

cat > "$OUT" <<EOF
class_name BuildInfoGen
## GENERATED by tools/stamp_build.sh — DO NOT EDIT, DO NOT COMMIT (git-ignored).
## Baked git short SHA of the build, read at runtime by systems/version.gd
## (BuildVersion.short_sha) so an exported binary knows its exact commit with no git.
const SHORT_SHA := "${SHA}"
EOF

echo "stamp_build: wrote $OUT with SHORT_SHA=\"${SHA}\""
